from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, cm
from reportlab.lib.colors import HexColor, black, white, grey
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from io import BytesIO
from datetime import datetime
from typing import Dict, List
import math


COLOR_PRIMARY = HexColor("#2563EB")
COLOR_SECONDARY = HexColor("#1E40AF")
COLOR_ACCENT = HexColor("#F59E0B")
COLOR_SUCCESS = HexColor("#10B981")
COLOR_TEXT = HexColor("#1F2937")
COLOR_TEXT_LIGHT = HexColor("#6B7280")
COLOR_BG = HexColor("#F9FAFB")
COLOR_BORDER = HexColor("#E5E7EB")


def generate_pdf_bytes(
    proposal_id: str,
    solver_name: str,
    problem_title: str,
    problem_ref: str,
    overall_score: float,
    dimension_scores: Dict[str, int],
    feedback: str,
    outline: Dict[str, str],
) -> bytes:
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    _draw_cover_page(c, width, height, proposal_id, solver_name, problem_title, problem_ref, overall_score)
    _draw_score_page(c, width, height, dimension_scores, feedback)
    
    for section_title, content in outline.items():
        _draw_section_page(c, width, height, section_title, content)
    
    _draw_footer(c, width, height, proposal_id)
    
    c.save()
    buffer.seek(0)
    return buffer.read()


def _draw_cover_page(c, width, height, proposal_id, solver_name, problem_title, problem_ref, overall_score):
    c.setFillColor(COLOR_BG)
    c.rect(0, 0, width, height, fill=1, stroke=0)
    
    c.setFillColor(COLOR_PRIMARY)
    c.rect(0, height - 120, width, 120, fill=1, stroke=0)
    
    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 36)
    c.drawString(40, height - 80, "PROPOSAL")
    
    c.setFont("Helvetica", 14)
    c.drawString(40, height - 110, f"SkillProof Verified Proposal  •  {datetime.now().strftime('%B %d, %Y')}")
    
    c.setFillColor(COLOR_TEXT)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(40, height - 200, problem_title[:80])
    
    c.setFont("Helvetica", 14)
    c.setFillColor(COLOR_TEXT_LIGHT)
    c.drawString(40, height - 240, f"Problem Reference: {problem_ref}")
    c.drawString(40, height - 265, f"Solver: {solver_name}")
    c.drawString(40, height - 290, f"Proposal ID: {proposal_id}")
    
    _draw_score_badge(c, width - 180, height - 280, overall_score)
    
    c.setFillColor(COLOR_PRIMARY)
    c.setFont("Helvetica", 10)
    c.drawString(40, 60, "Generated by SkillProof  •  No external AI models were used")
    
    c.showPage()


def _draw_score_badge(c, x, y, score):
    radius = 50
    c.setStrokeColor(COLOR_BORDER)
    c.setLineWidth(2)
    c.circle(x + radius, y + radius, radius, fill=0, stroke=1)
    
    angle_start = 90
    angle_extent = -3.6 * score * 10
    c.setStrokeColor(COLOR_PRIMARY if score >= 6 else COLOR_ACCENT)
    c.setLineWidth(8)
    c.setLineCap(1)
    p = c.beginPath()
    p.arc(x + radius, y + radius, radius - 4, angle_start, angle_start + angle_extent)
    c.drawPath(p, fill=0, stroke=1)
    
    c.setFillColor(COLOR_TEXT)
    c.setFont("Helvetica-Bold", 28)
    text = f"{score:.0f}/100"
    tw = c.stringWidth(text, "Helvetica-Bold", 28)
    c.drawString(x + radius - tw/2, y + radius - 10, text)
    
    c.setFont("Helvetica", 10)
    c.setFillColor(COLOR_TEXT_LIGHT)
    label = "OVERALL SCORE"
    lw = c.stringWidth(label, "Helvetica", 10)
    c.drawString(x + radius - lw/2, y - 20, label)


def _draw_score_page(c, width, height, dimension_scores, feedback):
    c.setFillColor(white)
    c.rect(0, 0, width, height, fill=1, stroke=0)
    
    c.setFillColor(COLOR_PRIMARY)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(40, height - 60, "Score Breakdown")
    
    c.setFont("Helvetica", 11)
    c.setFillColor(COLOR_TEXT_LIGHT)
    c.drawString(40, height - 90, "Six dimensions scored 1–10. Gate threshold: 60/100 average.")
    
    _draw_radar_chart(c, width/2, height - 320, dimension_scores)
    _draw_score_bars(c, 40, height - 420, dimension_scores)
    _draw_feedback_box(c, 40, 120, width - 80, feedback)
    
    c.showPage()


def _draw_radar_chart(c, cx, cy, scores):
    dimensions = list(scores.keys())
    n = len(dimensions)
    max_radius = 120
    ring_count = 5
    
    c.setStrokeColor(COLOR_BORDER)
    c.setLineWidth(0.5)
    
    for ring in range(1, ring_count + 1):
        r = max_radius * ring / ring_count
        _draw_polygon(c, cx, cy, r, n)
        c.drawPath(c.beginPath(), fill=0, stroke=1)
    
    for i in range(n):
        angle = math.radians(90 - i * 360 / n)
        x = cx + max_radius * math.cos(angle)
        y = cy + max_radius * math.sin(angle)
        c.line(cx, cy, x, y)
        
        label_x = cx + (max_radius + 15) * math.cos(angle)
        label_y = cy + (max_radius + 15) * math.sin(angle)
        c.setFont("Helvetica", 8)
        c.setFillColor(COLOR_TEXT)
        text = dimensions[i]
        tw = c.stringWidth(text, "Helvetica", 8)
        if math.cos(angle) > 0:
            c.drawString(label_x, label_y + 3, text)
        else:
            c.drawString(label_x - tw, label_y + 3, text)
    
    path = c.beginPath()
    first = True
    for i, dim in enumerate(dimensions):
        score = scores[dim]
        r = max_radius * score / 10
        angle = math.radians(90 - i * 360 / n)
        x = cx + r * math.cos(angle)
        y = cy + r * math.sin(angle)
        if first:
            path.moveTo(x, y)
            first = False
        else:
            path.lineTo(x, y)
    path.close()
    
    c.setFillColor(HexColor("#2563EB33"))
    c.setStrokeColor(COLOR_PRIMARY)
    c.setLineWidth(2)
    c.drawPath(path, fill=1, stroke=1)
    
    for i, dim in enumerate(dimensions):
        score = scores[dim]
        r = max_radius * score / 10
        angle = math.radians(90 - i * 360 / n)
        x = cx + r * math.cos(angle)
        y = cy + r * math.sin(angle)
        c.setFillColor(COLOR_PRIMARY)
        c.circle(x, y, 4, fill=1, stroke=0)


def _draw_polygon(c, cx, cy, r, n):
    path = c.beginPath()
    for i in range(n):
        angle = math.radians(90 - i * 360 / n)
        x = cx + r * math.cos(angle)
        y = cy + r * math.sin(angle)
        if i == 0:
            path.moveTo(x, y)
        else:
            path.lineTo(x, y)
    path.close()
    c.drawPath(path, fill=0, stroke=1)


def _draw_score_bars(c, x, y, scores):
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(COLOR_TEXT)
    c.drawString(x, y, "Dimension Scores")
    
    bar_y = y - 25
    bar_height = 18
    bar_max_width = 300
    
    for dim, score in scores.items():
        c.setFont("Helvetica", 10)
        c.setFillColor(COLOR_TEXT)
        c.drawString(x, bar_y + 4, dim)
        
        bar_width = bar_max_width * score / 10
        color = COLOR_SUCCESS if score >= 7 else (COLOR_ACCENT if score >= 5 else HexColor("#EF4444"))
        c.setFillColor(color)
        c.rect(x + 180, bar_y, bar_width, bar_height, fill=1, stroke=0)
        
        c.setFillColor(white if score >= 5 else COLOR_TEXT)
        c.setFont("Helvetica-Bold", 9)
        c.drawString(x + 180 + bar_width + 5, bar_y + 4, f"{score}/10")
        
        bar_y -= 28


def _draw_feedback_box(c, x, y, width, feedback):
    c.setFillColor(HexColor("#FEF3C7"))
    c.setStrokeColor(COLOR_ACCENT)
    c.setLineWidth(1)
    c.roundRect(x, y, width, 80, 5, fill=1, stroke=1)
    
    c.setFillColor(HexColor("#92400E"))
    c.setFont("Helvetica-Bold", 10)
    c.drawString(x + 10, y + 55, "Key Improvement:")
    
    c.setFont("Helvetica", 9)
    c.drawString(x + 10, y + 35, feedback[:120])
    if len(feedback) > 120:
        c.drawString(x + 10, y + 22, feedback[120:240])


def _draw_section_page(c, width, height, title, content):
    c.setFillColor(white)
    c.rect(0, 0, width, height, fill=1, stroke=0)
    
    c.setFillColor(COLOR_PRIMARY)
    c.rect(0, height - 60, width, 60, fill=1, stroke=0)
    
    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(40, height - 42, title)
    
    c.setFillColor(COLOR_TEXT)
    c.setFont("Helvetica", 11)
    
    text_obj = c.beginText(40, height - 100)
    text_obj.setLeading(16)
    
    for line in content.split('\n'):
        wrapped = _wrap_text(c, line, width - 80)
        for w in wrapped:
            text_obj.textLine(w)
        if not wrapped:
            text_obj.textLine("")
    
    c.drawText(text_obj)
    
    _draw_footer(c, width, height, "")
    c.showPage()


def _wrap_text(c, text, max_width):
    if not text:
        return [""]
    words = text.split(' ')
    lines = []
    current = ""
    for word in words:
        test = current + (" " if current else "") + word
        if c.stringWidth(test, "Helvetica", 11) <= max_width:
            current = test
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines if lines else [""]


def _draw_footer(c, width, height, proposal_id):
    c.setFillColor(COLOR_BG)
    c.rect(0, 0, width, 40, fill=1, stroke=0)
    
    c.setFillColor(COLOR_TEXT_LIGHT)
    c.setFont("Helvetica", 8)
    c.drawString(40, 12, f"Generated by SkillProof  •  Proposal ID: {proposal_id}  •  {datetime.now().isoformat()}")
    c.drawRightString(width - 40, 12, "No external AI models were used")